---
# https://docs.ansible.com/ansible-lint/rules/default_rules.html
skip_list:
  # Lines should be no longer than 160 chars
  - "204"
  # rsync used in place of synchronize module
  - "303"
# vim: syntax=yaml
...
