---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: instance
    image: registry.git.coop/webarch/containers/images/ansible:0.1
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - idempotence
